version: "3.0"
services:
  nginx:
    image: nginx:latest
    ports:
      - "${EXTERNAL_PORT:-8020}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - .:/var/www:cached
    depends_on:
      - database
    env_file:
      - .env

  database:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mysql
    container_name: ${APP_NAME}_database
    volumes:
      - ./fixtures:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3320:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8021}:80"
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}

volumes:
  app_log:
  nginx_log:
