
services:

  _defaults:
    autowire: true      
    autoconfigure: true 
    public: false      

  App\Custom\Solutions\woocommercecustom:
      decorates: App\Solutions\woocommerce
      decoration_priority: 5
